shared:
    api_key: <%= ENV["NEXOSIS_API_KEY"] %>
    secret_key_base: 0ac49659734b01a1c6c2f13f60727e3c7e340f4f2c01ea7007678213b33b7c11518e8066703731f9c994bd827c7ff1880bfdc5908366097de9ed72b2f7af25ce